# Generated by Django 5.2.4 on 2025-07-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('external_id', models.IntegerField()),
                ('external_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'at_identity_external_user',
            },
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role_per_app',
        ),
        migrations.RemoveConstraint(
            model_name='userorganization',
            name='unique_user_organization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='crm_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='storeloop_data',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('slug', 'app_context')},
        ),
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together={('user', 'organization')},
        ),
        migrations.AddField(
            model_name='externaluser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='externaluser',
            unique_together={('app_name', 'external_id')},
        ),
    ]
